/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = FeatureFlagsResponse.Builder.class
)
public final class FeatureFlagsResponse {
  private final Map<String, Boolean> featureFlags;

  private final Map<String, Map<String, Object>> configs;

  private final Map<String, Object> additionalProperties;

  private FeatureFlagsResponse(Map<String, Boolean> featureFlags,
      Map<String, Map<String, Object>> configs, Map<String, Object> additionalProperties) {
    this.featureFlags = featureFlags;
    this.configs = configs;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Map of feature flag names to evaluated boolean values.
   */
  @JsonProperty("featureFlags")
  public Map<String, Boolean> getFeatureFlags() {
    return featureFlags;
  }

  /**
   * @return Map of config names to arbitrary JSON objects.
   */
  @JsonProperty("configs")
  public Map<String, Map<String, Object>> getConfigs() {
    return configs;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof FeatureFlagsResponse && equalTo((FeatureFlagsResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(FeatureFlagsResponse other) {
    return featureFlags.equals(other.featureFlags) && configs.equals(other.configs);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.featureFlags, this.configs);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Map<String, Boolean> featureFlags = new LinkedHashMap<>();

    private Map<String, Map<String, Object>> configs = new LinkedHashMap<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(FeatureFlagsResponse other) {
      featureFlags(other.getFeatureFlags());
      configs(other.getConfigs());
      return this;
    }

    /**
     * <p>Map of feature flag names to evaluated boolean values.</p>
     */
    @JsonSetter(
        value = "featureFlags",
        nulls = Nulls.SKIP
    )
    public Builder featureFlags(Map<String, Boolean> featureFlags) {
      this.featureFlags.clear();
      if (featureFlags != null) {
        this.featureFlags.putAll(featureFlags);
      }
      return this;
    }

    public Builder putAllFeatureFlags(Map<String, Boolean> featureFlags) {
      if (featureFlags != null) {
        this.featureFlags.putAll(featureFlags);
      }
      return this;
    }

    public Builder featureFlags(String key, Boolean value) {
      this.featureFlags.put(key, value);
      return this;
    }

    /**
     * <p>Map of config names to arbitrary JSON objects.</p>
     */
    @JsonSetter(
        value = "configs",
        nulls = Nulls.SKIP
    )
    public Builder configs(Map<String, Map<String, Object>> configs) {
      this.configs.clear();
      if (configs != null) {
        this.configs.putAll(configs);
      }
      return this;
    }

    public Builder putAllConfigs(Map<String, Map<String, Object>> configs) {
      if (configs != null) {
        this.configs.putAll(configs);
      }
      return this;
    }

    public Builder configs(String key, Map<String, Object> value) {
      this.configs.put(key, value);
      return this;
    }

    public FeatureFlagsResponse build() {
      return new FeatureFlagsResponse(featureFlags, configs, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
