// This file was auto-generated by Fern from our API Definition.

/**
 * Evaluated feature flags and dynamic configs.
 */
export interface FeatureFlagsResponse {
    /** Map of feature flag names to evaluated boolean values. */
    featureFlags: Record<string, boolean>;
    /** Map of config names to arbitrary JSON objects. */
    configs: Record<string, Record<string, unknown>>;
}
