/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.featureflags;

import core.ClientOptions;
import core.RequestOptions;
import java.util.concurrent.CompletableFuture;
import types.FeatureFlagsResponse;

public class AsyncFeatureFlagsClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawFeatureFlagsClient rawClient;

  public AsyncFeatureFlagsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawFeatureFlagsClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawFeatureFlagsClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Returns all feature flags and configs for the project environment associated with the provided client API key. Feature flag values are evaluated for the optional user identifier.
   */
  public CompletableFuture<FeatureFlagsResponse> getFeatureFlags() {
    return this.rawClient.getFeatureFlags().thenApply(response -> response.body());
  }

  /**
   * Returns all feature flags and configs for the project environment associated with the provided client API key. Feature flag values are evaluated for the optional user identifier.
   */
  public CompletableFuture<FeatureFlagsResponse> getFeatureFlags(RequestOptions requestOptions) {
    return this.rawClient.getFeatureFlags(requestOptions).thenApply(response -> response.body());
  }
}
