/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.featureflags;

import com.fasterxml.jackson.core.JsonProcessingException;
import core.ClientOptions;
import core.LogoasApiApiException;
import core.LogoasApiException;
import core.LogoasApiHttpResponse;
import core.ObjectMappers;
import core.RequestOptions;
import errors.UnauthorizedError;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;
import types.FeatureFlagsResponse;

public class AsyncRawFeatureFlagsClient {
  protected final ClientOptions clientOptions;

  public AsyncRawFeatureFlagsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Returns all feature flags and configs for the project environment associated with the provided client API key. Feature flag values are evaluated for the optional user identifier.
   */
  public CompletableFuture<LogoasApiHttpResponse<FeatureFlagsResponse>> getFeatureFlags() {
    return getFeatureFlags(null);
  }

  /**
   * Returns all feature flags and configs for the project environment associated with the provided client API key. Feature flag values are evaluated for the optional user identifier.
   */
  public CompletableFuture<LogoasApiHttpResponse<FeatureFlagsResponse>> getFeatureFlags(
      RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("api/featureflags");if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      Request okhttpRequest = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json")
        .build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      CompletableFuture<LogoasApiHttpResponse<FeatureFlagsResponse>> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
              future.complete(new LogoasApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FeatureFlagsResponse.class), response));
              return;
            }
            try {
              if (response.code() == 401) {
                future.completeExceptionally(new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            future.completeExceptionally(new LogoasApiApiException("Error with status code " + response.code(), response.code(), errorBody, response));
            return;
          }
          catch (IOException e) {
            future.completeExceptionally(new LogoasApiException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new LogoasApiException("Network error executing HTTP request", e));
        }
      });
      return future;
    }
  }
