/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.featureflags;

import core.ClientOptions;
import core.RequestOptions;
import types.FeatureFlagsResponse;

public class FeatureFlagsClient {
  protected final ClientOptions clientOptions;

  private final RawFeatureFlagsClient rawClient;

  public FeatureFlagsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new RawFeatureFlagsClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public RawFeatureFlagsClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Returns all feature flags and configs for the project environment associated with the provided client API key. Feature flag values are evaluated for the optional user identifier.
   */
  public FeatureFlagsResponse getFeatureFlags() {
    return this.rawClient.getFeatureFlags().body();
  }

  /**
   * Returns all feature flags and configs for the project environment associated with the provided client API key. Feature flag values are evaluated for the optional user identifier.
   */
  public FeatureFlagsResponse getFeatureFlags(RequestOptions requestOptions) {
    return this.rawClient.getFeatureFlags(requestOptions).body();
  }
}
