/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.featureflags;

import com.fasterxml.jackson.core.JsonProcessingException;
import core.ClientOptions;
import core.LogoasApiApiException;
import core.LogoasApiException;
import core.LogoasApiHttpResponse;
import core.ObjectMappers;
import core.RequestOptions;
import errors.UnauthorizedError;
import java.io.IOException;
import java.lang.Object;
import java.lang.String;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;
import types.FeatureFlagsResponse;

public class RawFeatureFlagsClient {
  protected final ClientOptions clientOptions;

  public RawFeatureFlagsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Returns all feature flags and configs for the project environment associated with the provided client API key. Feature flag values are evaluated for the optional user identifier.
   */
  public LogoasApiHttpResponse<FeatureFlagsResponse> getFeatureFlags() {
    return getFeatureFlags(null);
  }

  /**
   * Returns all feature flags and configs for the project environment associated with the provided client API key. Feature flag values are evaluated for the optional user identifier.
   */
  public LogoasApiHttpResponse<FeatureFlagsResponse> getFeatureFlags(
      RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("api/featureflags");if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      Request okhttpRequest = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json")
        .build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        if (response.isSuccessful()) {
          return new LogoasApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FeatureFlagsResponse.class), response);
        }
        try {
          if (response.code() == 401) {
            throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
          }
        }
        catch (JsonProcessingException ignored) {
          // unable to map error response, throwing generic error
        }
        Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
        throw new LogoasApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
      }
      catch (IOException e) {
        throw new LogoasApiException("Network error executing HTTP request", e);
      }
    }
  }
