# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.feature_flags_response import FeatureFlagsResponse
from .raw_client import AsyncRawFeatureFlagsClient, RawFeatureFlagsClient


class FeatureFlagsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawFeatureFlagsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawFeatureFlagsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawFeatureFlagsClient
        """
        return self._raw_client

    def get_feature_flags(self, *, request_options: typing.Optional[RequestOptions] = None) -> FeatureFlagsResponse:
        """
        Returns all feature flags and configs for the project environment associated with the provided client API key. Feature flag values are evaluated for the optional user identifier.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FeatureFlagsResponse
            Evaluated feature flags and configs for the client environment.

        Examples
        --------
        from logoas import LogoasApi

        client = LogoasApi(
            user="YOUR_USER",
            api_key="YOUR_API_KEY",
        )
        client.feature_flags.get_feature_flags()
        """
        _response = self._raw_client.get_feature_flags(request_options=request_options)
        return _response.data


class AsyncFeatureFlagsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawFeatureFlagsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawFeatureFlagsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawFeatureFlagsClient
        """
        return self._raw_client

    async def get_feature_flags(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> FeatureFlagsResponse:
        """
        Returns all feature flags and configs for the project environment associated with the provided client API key. Feature flag values are evaluated for the optional user identifier.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FeatureFlagsResponse
            Evaluated feature flags and configs for the client environment.

        Examples
        --------
        import asyncio

        from logoas import AsyncLogoasApi

        client = AsyncLogoasApi(
            user="YOUR_USER",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.feature_flags.get_feature_flags()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_feature_flags(request_options=request_options)
        return _response.data
