// This file was auto-generated by Fern from our API Definition.

export const LogoasApiEnvironment = {
    Production: "https://featureflags.logoas.xyz",
} as const;

export type LogoasApiEnvironment = typeof LogoasApiEnvironment.Production;
