# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class FeatureFlagsResponse(UniversalBaseModel):
    """
    Evaluated feature flags and dynamic configs.
    """

    feature_flags: typing_extensions.Annotated[
        typing.Dict[str, bool],
        FieldMetadata(alias="featureFlags"),
        pydantic.Field(alias="featureFlags", description="Map of feature flag names to evaluated boolean values."),
    ]
    configs: typing.Dict[str, typing.Dict[str, typing.Any]] = pydantic.Field()
    """
    Map of config names to arbitrary JSON objects.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
