/**
 * This file was auto-generated by Fern from our API Definition.
 */

import core.ClientOptions;
import core.Suppliers;
import java.util.function.Supplier;
import resources.featureflags.AsyncFeatureFlagsClient;

public class AsyncLogoasApiClient {
  protected final ClientOptions clientOptions;

  protected final Supplier<AsyncFeatureFlagsClient> featureFlagsClient;

  public AsyncLogoasApiClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.featureFlagsClient = Suppliers.memoize(() -> new AsyncFeatureFlagsClient(clientOptions));
  }

  public AsyncFeatureFlagsClient featureFlags() {
    return this.featureFlagsClient.get();
  }

  public static AsyncLogoasApiClientBuilder builder() {
    return new AsyncLogoasApiClientBuilder();
  }
}
