/**
 * This file was auto-generated by Fern from our API Definition.
 */

import core.ClientOptions;
import core.Suppliers;
import java.util.function.Supplier;
import resources.featureflags.FeatureFlagsClient;

public class LogoasApiClient {
  protected final ClientOptions clientOptions;

  protected final Supplier<FeatureFlagsClient> featureFlagsClient;

  public LogoasApiClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.featureFlagsClient = Suppliers.memoize(() -> new FeatureFlagsClient(clientOptions));
  }

  public FeatureFlagsClient featureFlags() {
    return this.featureFlagsClient.get();
  }

  public static LogoasApiClientBuilder builder() {
    return new LogoasApiClientBuilder();
  }
}
